### ISSUE TITLE
Duplicate pip_sign_save ?

### ISSUE THREAD

**Issue by shahronak47** [PIP-Technical-Team/pipaux#95]
Hi @randrescastaneda , I observed that we have two `pip_sign_save` functions, one in `pipaux` and another one in `pipfun`. Do we need them both?

**Comment by randrescastaneda** [comment]
Hi @shahronak47 , 
No, we don't need them both. we need the one in `pipfun`. You will see that the one in `pipaux` is deprecated. 
Best,
